<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Frontend</title>
  <base href="./">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="frontend/styles.34c57ab7888ec1573f9c.css"></head>
<body>
  <app-root>Loading...</app-root>
  <script type="text/javascript" src="frontend/runtime.a66f828dca56eeb90e02.js"></script>
<script type="text/javascript" src="frontend/polyfills.2f4a59095805af02bd79.js"></script>
<script type="text/javascript" src="frontend/main.dc5700c118c0741a6e86.js"></script></body>
</html>